---
- hosts: 
    - all
    - dev-local
    - dev-remote
    - dev-vagrant
  sudo: true
  roles: 
    - common-config-project-dir
    - common-system
    - common-packages
    - prereq-git
    - prereq-nodejs
    - prereq-nodejs-packages
    - prereq-ruby
    - prereq-ruby-packages
    - stack-db-postgres
    - stack-nginx
    - stack-php
    - stack-php-symfony
    - stack-php-composer
