- hosts: all
  sudo: true
  roles: 
    - common-system
    - common-packages
    - prereq-git
    - prereq-nodejs
    - prereq-nodejs-packages
    - prereq-ruby
    - prereq-ruby-packages
    - stack-db-postgres
    - stack-nginx
    - stack-php
